### PR TITLE
[WIP] Bump GCC/newlib to 10.1 with C++ support

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
This is an attempt to solve #25 - a draft for now, let's see how far will we get with the CI.

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM, if CI says yes.

**Review by mithro — APPROVED** [review]
LGTM, if CI says yes.

**Comment by mithro** [comment]
After this is merged, we should most certainly;
 (a) Move to gcc-11.2.0.tar.xz which seems to be the latest version?
 (b) Set up some type of notification that our packages are behind the latest GCC released version?

**Comment by PiotrZierhoffer** [comment]
Not there yet: https://github.com/hdl/conda-compilers/pull/26/checks?check_run_id=3528719006#step:3:7469

**Comment by tcal-x** [comment]
This might be the actual error:
```
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking whether ln -s works... yes
  configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.
  make[1]: *** [Makefile:11270: configure-target-libstdc++-v3] Error 1
  make[1]: *** Waiting for unfinished jobs....
```

**Comment by tcal-x** [comment]
> This might be the actual error:

...exactly what you pointed to :) 

I guess I didn't wait long enough for the entire log to come in.

**Comment by PiotrZierhoffer** [comment]
This is now developed as  #31

**Pull request closed without merging**
