### PR TITLE
Update gcc to 10.1 and turn C++ support on

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
These changes update gcc to 10.1 and add C++ support for gcc with newlib.

This addresses #25.

Simply adding `c++` to `--enable-lanaguages` does not work, as libstdc++-v3 compilation fails (example in [run#3559265510](https://github.com/hdl/conda-compilers/runs/3559265510)).

<details><summary>Relevant error

</summary>

```
2021-09-09T17:50:07.1357393Z checking for EOWNERDEAD... no
2021-09-09T17:50:07.4128896Z configure: WARNING: uchar.h: present but cannot be compiled
2021-09-09T17:50:07.4131294Z configure: WARNING: uchar.h:     check for missing prerequisite headers?
2021-09-09T17:50:07.4132244Z configure: WARNING: uchar.h: see the Autoconf documentation
2021-09-09T17:50:07.4133308Z configure: WARNING: uchar.h:     section "Present But Cannot Be Compiled"
2021-09-09T17:50:07.4135065Z configure: WARNING: uchar.h: proceeding with the compiler's result
2021-09-09T17:50:07.4752788Z configure: WARNING: sys/ioctl.h: present but cannot be compiled
2021-09-09T17:50:07.4753965Z configure: WARNING: sys/ioctl.h:     check for missing prerequisite headers?
2021-09-09T17:50:07.4754907Z configure: WARNING: sys/ioctl.h: see the Autoconf documentation
2021-09-09T17:50:07.4755833Z configure: WARNING: sys/ioctl.h:     section "Present But Cannot Be Compiled"
2021-09-09T17:50:07.4757419Z configure: WARNING: sys/ioctl.h: proceeding with the compiler's result
2021-09-09T17:50:07.5768378Z configure: WARNING: sys/uio.h: present but cannot be compiled
2021-09-09T17:50:07.5769546Z configure: WARNING: sys/uio.h:     check for missing prerequisite headers?
2021-09-09T17:50:07.5770469Z configure: WARNING: sys/uio.h: see the Autoconf documentation
2021-09-09T17:50:07.5771395Z configure: WARNING: sys/uio.h:     section "Present But Cannot Be Compiled"
2021-09-09T17:50:07.5772939Z configure: WARNING: sys/uio.h: proceeding with the compiler's result
2021-09-09T17:50:07.6197657Z configure: WARNING: fenv.h: present but cannot be compiled
2021-09-09T17:50:07.6198800Z configure: WARNING: fenv.h:     check for missing prerequisite headers?
2021-09-09T17:50:07.6199751Z configure: WARNING: fenv.h: see the Autoconf documentation
2021-09-09T17:50:07.6200656Z configure: WARNING: fenv.h:     section "Present But Cannot Be Compiled"
2021-09-09T17:50:07.6202142Z configure: WARNING: fenv.h: proceeding with the compiler's result
2021-09-09T17:50:07.6947584Z configure: WARNING: stdbool.h: present but cannot be compiled
2021-09-09T17:50:07.6948809Z configure: WARNING: stdbool.h:     check for missing prerequisite headers?
2021-09-09T17:50:07.6949778Z configure: WARNING: stdbool.h: see the Autoconf documentation
2021-09-09T17:50:07.6950705Z configure: WARNING: stdbool.h:     section "Present But Cannot Be Compiled"
2021-09-09T17:50:07.6952214Z configure: WARNING: stdbool.h: proceeding with the compiler's result
2021-09-09T17:50:07.7243875Z configure: WARNING: stdalign.h: present but cannot be compiled
2021-09-09T17:50:07.7244944Z configure: WARNING: stdalign.h:     check for missing prerequisite headers?
2021-09-09T17:50:07.7245921Z configure: WARNING: stdalign.h: see the Autoconf documentation
2021-09-09T17:50:07.7246856Z configure: WARNING: stdalign.h:     section "Present But Cannot Be Compiled"
2021-09-09T17:50:07.7248348Z configure: WARNING: stdalign.h: proceeding with the compiler's result
2021-09-09T17:50:07.7541210Z configure: error: computing EOF failed
2021-09-09T17:50:07.7953876Z make[1]: *** [Makefile:11271: configure-target-libstdc++-v3] Error 1
2021-09-09T17:50:07.7960292Z make: *** [Makefile:954: all] Error 2
```
</details>

Updating `--prefix` config option helps and fixes compilation process.

<details><summary>Unfortunately it doesn't run properly.</summary>

```
$ riscv32-elf-g++ main.cpp
riscv32-elf-g++: fatal error: cannot read spec file '/home/user/conda/miniconda3/envs/gcc/lib/gcc/': Is a directory
compilation terminated.

$ riscv32-elf-gcc main.cpp
riscv32-elf-gcc: error: main.cpp: C++ compiler not installed on this system

$ riscv32-elf-newlib-g++ main.cpp
riscv32-elf-newlib-g++: fatal error: cannot read spec file '/home/user/conda/miniconda3/envs/gcc/lib/gcc/': Is a directory
compilation terminated.

$ cat main.cpp
#include <iostream>

using namespace std;

int main(){
        cout << "Hello World!" << endl;
        bool x = true;
        return x;
}
```
</details>
  
`conda-build` rewrites the internal paths to get rid of the build prefix, but then gcc  fails to locate necessary files. We can investigate that further in the next step.

Adding `build/detect_binary_files_with_prefix: False` value to _gcc/newlib/meta.yaml_ partially fixes the problem.

gcc and g++ work correctly now, but simple `strings` execution reveals, that paths from build process are still present in the binaries.
It doesn't seem to affect the gcc functionality though.

### CODE REVIEW

**Comment by PiotrZierhoffer** [comment]
FYI @mithro, @tcal-x

**Comment by mithro** [comment]
It sounds like there is an issue around sysroot -- see https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html ?

There might be useful information in https://elinux.org/images/1/15/Anatomy_of_Cross-Compilation_Toolchains.pdf and https://www.linuxfromscratch.org/lfs/view/stable/chapter05/glibc.html ?

**Comment by mithro** [comment]
There is some talk about how libstdc++ and stuff need to be deferred as part of cross compiling at https://www.linuxfromscratch.org/lfs/view/stable/chapter05/gcc-libstdc++-pass1.html

**Comment by mithro** [comment]
See also https://wiki.osdev.org/GCC_Cross-Compiler

**Comment by PiotrZierhoffer** [comment]
For some reason the upload hangs, but all other jobs passed. Merging, I suspect a github hiccup here

**Pull request merged**
